# jwt signing keys (AD-07a/b, M3): auth signs with the private key, every service verifies with the public key.
# generated by terraform so no manual key step is lost with the ephemeral vdi; the private key therefore also
# lives in terraform state (the participant-only state bucket, which already holds the database password).

locals {
  is_cloud        = data.aws_caller_identity.this.id != "000000000000"
  jwt_secret_name = format("%s-jwt-signing-%s", var.aws_project, local.app_id)

  # only auth may sign: in the cloud it fetches the key from secrets manager, locally it gets it directly
  # (AD-07b: local development does not depend on localstack's secrets manager emulation)
  auth_env_vars = local.is_cloud ? {
    JWT_SECRET_NAME = local.jwt_secret_name
    } : {
    JWT_PRIVATE_KEY = tls_private_key.jwt.private_key_pem
  }
}

resource "tls_private_key" "jwt" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

# the name matches the existing iam grant in policy.tftpl: secret:${app_name}*${app_id}*
resource "aws_secretsmanager_secret" "jwt" {
  count = local.is_cloud ? 1 : 0
  name  = local.jwt_secret_name
  # ephemeral workshop environment: allow immediate re-creation after a teardown
  recovery_window_in_days = 0
  tags                    = local.app_tags
}

resource "aws_secretsmanager_secret_version" "jwt" {
  count         = local.is_cloud ? 1 : 0
  secret_id     = aws_secretsmanager_secret.jwt[0].id
  secret_string = tls_private_key.jwt.private_key_pem
}
